### ISSUE TITLE
The server crashed 

### ISSUE THREAD

**Issue by gswxy** [Gozzim/mod-npc-spectator#2]
The server crashed while watching the 3V3

**Comment by yuanf225** [comment]
It would be nice if you could attach the crash log
Which modules are used, the core hashes, which are easy for the author to check

**Comment by Gozzim** [comment]
Exactly as @yuanf225 said. Please provide more information on how the crash occured and error logs of possible. The NPC only helps you join the match. A crash during the match without any interaction with the NPC at that time, as suggested by your current issue, is unlikely.

A more detailed description of what you did during that time and the logs could give me  a better insight. 

Sadly I cannot put a lot of time into my repos (including maintenance) and AC in general lately since I have been working 80 weeks which will continue until the end of October. But I can try to find the time this weekend.

Of course you are always welcome to open a PR if you have already fixed the issue :)

**Comment by w5860363** [comment]
Confirmed, crash occurred when clicking the 3V3 button
